package tn.isetrades.test10.entity.model;
// Generated Jun 11, 2018 2:10:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Flavor generated by hbm2java
 */
@Entity
@Table(name="flavor"
    ,catalog="test10"
)
public class Flavor  implements java.io.Serializable {


     private Integer idFlavor;
     private long disk;
     private String name;
     private long ram;
     private float rxtx;
     private int vcpus;
     private byte visibility;
     private int swap;
     private int ephemeral;
     private Set<Server> servers = new HashSet<Server>(0);

    public Flavor() {
    }

	
    public Flavor(long disk, String name, long ram, float rxtx, int vcpus, byte visibility, int swap, int ephemeral) {
        this.disk = disk;
        this.name = name;
        this.ram = ram;
        this.rxtx = rxtx;
        this.vcpus = vcpus;
        this.visibility = visibility;
        this.swap = swap;
        this.ephemeral = ephemeral;
    }
    public Flavor(long disk, String name, long ram, float rxtx, int vcpus, byte visibility, int swap, int ephemeral, Set<Server> servers) {
       this.disk = disk;
       this.name = name;
       this.ram = ram;
       this.rxtx = rxtx;
       this.vcpus = vcpus;
       this.visibility = visibility;
       this.swap = swap;
       this.ephemeral = ephemeral;
       this.servers = servers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_flavor", unique=true, nullable=false)
    public Integer getIdFlavor() {
        return this.idFlavor;
    }
    
    public void setIdFlavor(Integer idFlavor) {
        this.idFlavor = idFlavor;
    }

    
    @Column(name="disk", nullable=false)
    public long getDisk() {
        return this.disk;
    }
    
    public void setDisk(long disk) {
        this.disk = disk;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ram", nullable=false)
    public long getRam() {
        return this.ram;
    }
    
    public void setRam(long ram) {
        this.ram = ram;
    }

    
    @Column(name="rxtx", nullable=false, precision=12, scale=0)
    public float getRxtx() {
        return this.rxtx;
    }
    
    public void setRxtx(float rxtx) {
        this.rxtx = rxtx;
    }

    
    @Column(name="vcpus", nullable=false)
    public int getVcpus() {
        return this.vcpus;
    }
    
    public void setVcpus(int vcpus) {
        this.vcpus = vcpus;
    }

    
    @Column(name="visibility", nullable=false)
    public byte getVisibility() {
        return this.visibility;
    }
    
    public void setVisibility(byte visibility) {
        this.visibility = visibility;
    }

    
    @Column(name="swap", nullable=false)
    public int getSwap() {
        return this.swap;
    }
    
    public void setSwap(int swap) {
        this.swap = swap;
    }

    
    @Column(name="ephemeral", nullable=false)
    public int getEphemeral() {
        return this.ephemeral;
    }
    
    public void setEphemeral(int ephemeral) {
        this.ephemeral = ephemeral;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="flavor")
    public Set<Server> getServers() {
        return this.servers;
    }
    
    public void setServers(Set<Server> servers) {
        this.servers = servers;
    }




}


