package tn.isetrades.test10.entity.model;
// Generated Jun 11, 2018 2:10:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="image"
    ,catalog="test10"
)
public class Image  implements java.io.Serializable {


     private Integer idImage;
     private Set<Server> servers = new HashSet<Server>(0);

    public Image() {
    }

    public Image(Set<Server> servers) {
       this.servers = servers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_image", unique=true, nullable=false)
    public Integer getIdImage() {
        return this.idImage;
    }
    
    public void setIdImage(Integer idImage) {
        this.idImage = idImage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="image")
    public Set<Server> getServers() {
        return this.servers;
    }
    
    public void setServers(Set<Server> servers) {
        this.servers = servers;
    }




}


